# Generated by Django 4.2.9 on 2024-01-09 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پاسخ'), ('answered', 'پاسخ داده شده'), ('closed', 'بسته شده')], default='pending', max_length=255, verbose_name='وضعیت')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('section', models.CharField(choices=[('مدیریت', 'مدیریت'), ('مالی', 'مالی'), ('پشتیبانی', 'پشتیبانی')], max_length=128, verbose_name='بخش مربوطه')),
                ('priority', models.CharField(choices=[('کم', 'کم'), ('متوسط', 'متوسط'), ('زیاد', 'زیاد')], default='کم', max_length=128, verbose_name='اولویت')),
                ('seen_by_user', models.BooleanField(default=False, verbose_name='دیده شده توسط کاربر')),
                ('seen_by_admin', models.BooleanField(default=False, verbose_name='دیده شده توسط ادمین')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تیکت',
                'verbose_name_plural': 'تیکت ها',
            },
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='پیام')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پیام تیکت',
                'verbose_name_plural': 'پیام های تیکت',
            },
        ),
    ]
