# Generated by Django 5.1.2 on 2024-10-29 13:01

import django.db.models.deletion
import ticket.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[(ticket.models.TicketOptions['PENDING'], ticket.models.TicketOptions['PENDING_LABEL']), (ticket.models.TicketOptions['ANSWERED'], ticket.models.TicketOptions['ANSWERED_LABEL']), (ticket.models.TicketOptions['CLOSED'], ticket.models.TicketOptions['CLOSED_LABEL'])], default=ticket.models.TicketOptions['PENDING'], max_length=255)),
                ('section', models.CharField(choices=[(ticket.models.TicketOptions['MANAGEMENT'], ticket.models.TicketOptions['MANAGEMENT_LABEL']), (ticket.models.TicketOptions['FINANCES'], ticket.models.TicketOptions['FINANCES_LABEL']), (ticket.models.TicketOptions['SUPPORT'], ticket.models.TicketOptions['SUPPORT_LABEL'])], default=ticket.models.TicketOptions['SUPPORT'], max_length=128)),
                ('priority', models.CharField(choices=[(ticket.models.TicketOptions['LOW'], ticket.models.TicketOptions['LOW_LABEL']), (ticket.models.TicketOptions['MEDIUM'], ticket.models.TicketOptions['MEDIUM_LABEL']), (ticket.models.TicketOptions['HIGH_LABEL'], ticket.models.TicketOptions['HIGH_LABEL'])], default=ticket.models.TicketOptions['LOW'], max_length=128)),
                ('seen_by_user', models.BooleanField(default=False, verbose_name='Seen by user')),
                ('seen_by_admin', models.BooleanField(default=False, verbose_name='Seen by admin')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('soft_delete', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
            },
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('viewed', models.DateTimeField(null=True)),
                ('soft_delete', models.BooleanField(default=False)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('viewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_viewer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket Message',
                'verbose_name_plural': 'Ticket Messages',
            },
        ),
    ]
